source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'classifier-reborn'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-regex-replace'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-tabs'
    gem 'jekyll-toc'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'i18n'
    gem 'kramdown'
    gem 'rouge'
    gem 'nokogiri'
    gem 'uglifier'
    gem 'loofah'
    gem 'concurrent-ruby'
    gem 'minitest'
    gem 'connection_pool'
    gem 'strscan'
    gem 'mutex_m'
    gem 'json'
    gem 'execjs'
    gem 'rexml'
    gem 'csv'
    gem 'observer'
end
group :other_plugins do
    gem 'css_parser'
    gem 'feedjira'
    gem 'httparty'
end
